sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: a8700998

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJpQqCf1VzLL79TXVrp
    access-key-secret: JIeBz6mIfDHjxVfMn0QOabRtvr1Qd3
    bucket-name: take-out-buck

  redis:
    host: localhost
    port: 6379
    password: a8700998
    database: 0

  wechat:
    appid: wx0b6dc30c2a0b3d1f
    secret: b3ecc90a3b394f885ed94a5f0960224e
